<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BarangSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('barangs')->insert([
            // ===== LAB 1 =====
            [
                'kode_barang' => 'LAB1-KOM01',
                'nama_barang' => 'Komputer Rakitan Core i5',
                'kategori_id' => 1, // Perangkat Elektronik
                'lokasi_id' => 1, // LAB 1
                'sumberdana_id' => 1,
                'jumlah' => 10,
                'satuan' => 'Unit',
                'jumlah_baik' => 10,
                'jumlah_rusak_ringan' => 0,
                'jumlah_rusak_berat' => 0,
                'tanggal_pengadaan' => '2023-01-10',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'LAB1-PRJ01',
                'nama_barang' => 'Proyektor Epson XGA',
                'kategori_id' => 1,
                'lokasi_id' => 1,
                'sumberdana_id' => 2,
                'jumlah' => 1,
                'satuan' => 'Unit',
                'jumlah_baik' => 1,
                'jumlah_rusak_ringan' => 0,
                'jumlah_rusak_berat' => 0,
                'tanggal_pengadaan' => '2022-05-20',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'LAB1-RTR01',
                'nama_barang' => 'Router TP-Link 8 Port',
                'kategori_id' => 2, // Peralatan Jaringan & Teknologi
                'lokasi_id' => 1,
                'sumberdana_id' => 3,
                'jumlah' => 1,
                'satuan' => 'Unit',
                'jumlah_baik' => 1,
                'jumlah_rusak_ringan' => 0,
                'jumlah_rusak_berat' => 0,
                'tanggal_pengadaan' => '2023-06-15',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'LAB1-MJK01',
                'nama_barang' => 'Meja Komputer Kayu',
                'kategori_id' => 3, // Perabotan & Fasilitas Ruangan
                'lokasi_id' => 1,
                'sumberdana_id' => 1,
                'jumlah' => 10,
                'satuan' => 'Buah',
                'jumlah_baik' => 9,
                'jumlah_rusak_ringan' => 1,
                'jumlah_rusak_berat' => 0,
                'tanggal_pengadaan' => '2023-03-10',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'LAB1-MPW01',
                'nama_barang' => 'Modul Pemrograman Web',
                'kategori_id' => 4, // Dokumentasi & Administrasi
                'lokasi_id' => 1,
                'sumberdana_id' => 2,
                'jumlah' => 10,
                'satuan' => 'Buku',
                'jumlah_baik' => 9,
                'jumlah_rusak_ringan' => 1,
                'jumlah_rusak_berat' => 0,
                'tanggal_pengadaan' => '2024-01-05',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== LAB 2 =====
            [
                'kode_barang' => 'LAB2-KOM02',
                'nama_barang' => 'Komputer Rakitan Core i7',
                'kategori_id' => 1,
                'lokasi_id' => 2,
                'sumberdana_id' => 1,
                'jumlah' => 12,
                'satuan' => 'Unit',
                'jumlah_baik' => 11,
                'jumlah_rusak_ringan' => 1,
                'jumlah_rusak_berat' => 0,
                'tanggal_pengadaan' => '2024-02-12',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'LAB2-PRN01',
                'nama_barang' => 'Printer Canon PIXMA G2020',
                'kategori_id' => 1,
                'lokasi_id' => 2,
                'sumberdana_id' => 2,
                'jumlah' => 2,
                'satuan' => 'Unit',
                'jumlah_baik' => 2,
                'jumlah_rusak_ringan' => 0,
                'jumlah_rusak_berat' => 0,
                'tanggal_pengadaan' => '2022-12-18',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'LAB2-RTR02',
                'nama_barang' => 'Switch D-Link 16 Port',
                'kategori_id' => 2,
                'lokasi_id' => 2,
                'sumberdana_id' => 3,
                'jumlah' => 1,
                'satuan' => 'Unit',
                'jumlah_baik' => 1,
                'jumlah_rusak_ringan' => 0,
                'jumlah_rusak_berat' => 0,
                'tanggal_pengadaan' => '2023-08-14',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'LAB2-KRS01',
                'nama_barang' => 'Kursi Putar Ergonomis',
                'kategori_id' => 3,
                'lokasi_id' => 2,
                'sumberdana_id' => 1,
                'jumlah' => 12,
                'satuan' => 'Buah',
                'jumlah_baik' => 11,
                'jumlah_rusak_ringan' => 1,
                'jumlah_rusak_berat' => 0,
                'tanggal_pengadaan' => '2023-07-10',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'LAB2-MPR01',
                'nama_barang' => 'Modul Jaringan Komputer',
                'kategori_id' => 4,
                'lokasi_id' => 2,
                'sumberdana_id' => 2,
                'jumlah' => 10,
                'satuan' => 'Buku',
                'jumlah_baik' => 10,
                'jumlah_rusak_ringan' => 0,
                'jumlah_rusak_berat' => 0,
                'tanggal_pengadaan' => '2024-01-15',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== LAB 3 =====
            [
                'kode_barang' => 'LAB3-PC01',
                'nama_barang' => 'PC Rakitan Ryzen 5',
                'kategori_id' => 1,
                'lokasi_id' => 3,
                'sumberdana_id' => 1,
                'jumlah' => 8,
                'satuan' => 'Unit',
                'jumlah_baik' => 8,
                'jumlah_rusak_ringan' => 0,
                'jumlah_rusak_berat' => 0,
                'tanggal_pengadaan' => '2023-09-10',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'LAB3-SCN01',
                'nama_barang' => 'Scanner Epson Perfection V39',
                'kategori_id' => 1,
                'lokasi_id' => 3,
                'sumberdana_id' => 2,
                'jumlah' => 1,
                'satuan' => 'Unit',
                'jumlah_baik' => 1,
                'jumlah_rusak_ringan' => 0,
                'jumlah_rusak_berat' => 0,
                'tanggal_pengadaan' => '2023-05-05',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'LAB3-HBL01',
                'nama_barang' => 'Hub Gigabit 8 Port',
                'kategori_id' => 2,
                'lokasi_id' => 3,
                'sumberdana_id' => 3,
                'jumlah' => 2,
                'satuan' => 'Unit',
                'jumlah_baik' => 2,
                'jumlah_rusak_ringan' => 0,
                'jumlah_rusak_berat' => 0,
                'tanggal_pengadaan' => '2022-08-21',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'LAB3-LMP01',
                'nama_barang' => 'Lampu LED Philips 18W',
                'kategori_id' => 3,
                'lokasi_id' => 3,
                'sumberdana_id' => 1,
                'jumlah' => 12,
                'satuan' => 'Buah',
                'jumlah_baik' => 11,
                'jumlah_rusak_ringan' => 1,
                'jumlah_rusak_berat' => 0,
                'tanggal_pengadaan' => '2024-03-09',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'LAB3-MDK01',
                'nama_barang' => 'Modul Desain Grafis',
                'kategori_id' => 4,
                'lokasi_id' => 3,
                'sumberdana_id' => 2,
                'jumlah' => 10,
                'satuan' => 'Buku',
                'jumlah_baik' => 9,
                'jumlah_rusak_ringan' => 1,
                'jumlah_rusak_berat' => 0,
                'tanggal_pengadaan' => '2024-04-01',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== RUANG UKS =====
            [
                'kode_barang' => 'UKS-TMP01',
                'nama_barang' => 'Tempat Tidur Pasien',
                'kategori_id' => 5, // Kesehatan & Medis
                'lokasi_id' => 4,
                'sumberdana_id' => 1,
                'jumlah' => 2,
                'satuan' => 'Unit',
                'jumlah_baik' => 2,
                'jumlah_rusak_ringan' => 0,
                'jumlah_rusak_berat' => 0,
                'tanggal_pengadaan' => '2023-06-20',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'UKS-TNS01',
                'nama_barang' => 'Tensimeter Digital Omron',
                'kategori_id' => 5,
                'lokasi_id' => 4,
                'sumberdana_id' => 2,
                'jumlah' => 1,
                'satuan' => 'Unit',
                'jumlah_baik' => 1,
                'jumlah_rusak_ringan' => 0,
                'jumlah_rusak_berat' => 0,
                'tanggal_pengadaan' => '2024-01-20',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'UKS-PTR01',
                'nama_barang' => 'P3K Kit Lengkap',
                'kategori_id' => 5,
                'lokasi_id' => 4,
                'sumberdana_id' => 3,
                'jumlah' => 3,
                'satuan' => 'Set',
                'jumlah_baik' => 3,
                'jumlah_rusak_ringan' => 0,
                'jumlah_rusak_berat' => 0,
                'tanggal_pengadaan' => '2024-03-25',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'UKS-MJR01',
                'nama_barang' => 'Meja Periksa Pasien',
                'kategori_id' => 3,
                'lokasi_id' => 4,
                'sumberdana_id' => 1,
                'jumlah' => 1,
                'satuan' => 'Unit',
                'jumlah_baik' => 1,
                'jumlah_rusak_ringan' => 0,
                'jumlah_rusak_berat' => 0,
                'tanggal_pengadaan' => '2023-08-12',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'UKS-LMK01',
                'nama_barang' => 'Lemari Obat Kaca',
                'kategori_id' => 3,
                'lokasi_id' => 4,
                'sumberdana_id' => 2,
                'jumlah' => 1,
                'satuan' => 'Unit',
                'jumlah_baik' => 1,
                'jumlah_rusak_ringan' => 0,
                'jumlah_rusak_berat' => 0,
                'tanggal_pengadaan' => '2024-05-10',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
